
<html>
    <head>

        <title><?php //echo $titre;   ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" href="/MVC/css/style.css" />


    </head>
    <body>
        <div id="contain">
            <div id="connec">
                <h3>Connexion</h3>
                <hr />
                <br />
                <?php
                    $form = new Form_vue($this->getDatavue("form"));
                    echo $form->getHTML();
                ?>
            </div>
        </div>
    </body>
</html>