
<html>
    <head>

        <title><?php //echo $titre;   ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" href="/MVC/css/style.css" />


    </head>
    <body>
        <div id="contain">
            <div id="connec">
                <h3>Connexion</h3>
                <hr />
                <form action="" method="post">
                    <table>
                        <tr>
                            <td>Nom d'utilisateur </td>  <td> <input type="text" maxlength="50" name="login"> </td>
                        </tr>

                        <tr>
                            <td>Mot de passe </td>  <td>  <input type="text" maxlength="50" name="pdw"></td>
                        </tr>

                        <tr>
                            <td> <input  type="submit" value="Validez"  />  </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </body>
</html>